// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Spotifi.Models;

namespace Spotifi.Migrations
{
    [DbContext(typeof(SpotifiContext))]
    partial class SpotifiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Spotifi.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BandaId");

                    b.Property<string>("Nombre");

                    b.HasKey("Id");

                    b.HasIndex("BandaId");

                    b.ToTable("Albumes");
                });

            modelBuilder.Entity("Spotifi.Models.GrupoMusical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Foto");

                    b.Property<string>("Nombre")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Bandas");
                });

            modelBuilder.Entity("Spotifi.Models.Album", b =>
                {
                    b.HasOne("Spotifi.Models.GrupoMusical", "Banda")
                        .WithMany("Albumes")
                        .HasForeignKey("BandaId");
                });
#pragma warning restore 612, 618
        }
    }
}
